[package]
name = "battle_tanks"
version = "0.1.0"
authors = [
    "Delyan Dobrev <delqn.dobrev@gmail.com>",
    "Nikola Stoyanov <ns.barzakov@gmail.com>"]

[dependencies]
engine = {path = "../engine"}
gl = "^0.5.0"
cgmath = "^0.7.0"

[dependencies.glfw]
version = "^0.3.0"
default-features = false
