[package]
name = "engine"
version = "0.1.0"
authors = [
    "Delyan Dobrev <delqn.dobrev@gmail.com>",
    "Nikola Stoyanov <ns.barzakov@gmail.com>"]

[dependencies]
gl = "^0.6.0"
cgmath = "^0.9.1"
bit-vec = "^0.4.3"

[dependencies.glfw]
version = "^0.5.0"
default-features = false
