[package]
name = "engine"
version = "0.1.0"
authors = [
    "Delyan Dobrev <delqn.dobrev@gmail.com>",
    "Nikola Stoyanov <ns.barzakov@gmail.com>"]

[dependencies]
gl = "^0.6.1"
cgmath = "^0.12.0"

[dependencies.glfw]
version = "^0.10.0"
default-features = false
